// Sheets actions
export const FETCH_SHEETS   		= 'FETCH_SHEETS';
export const RECEIVE_SHEETS         = 'RECEIVE_SHEETS';
export const START_DELETING_SHEETS  = 'START_DELETING_SHEETS';
export const FINISH_DELETING_SHEETS = 'FINISH_DELETING_SHEETS';  
export const START_CREATING_SHEET	= 'START_CREATING_SHEET';
export const FINISH_CREATING_SHEET	= 'FINISH_CREATING_SHEET';
export const START_FETCHING_SHEET	= 'START_FETCHING_SHEET';
export const FINISH_FETCHING_SHEET	= 'FINISH_FETCHING_SHEET';
export const START_UPDATING_SHEET	= 'START_UPDATING_SHEET';
export const FINISH_UPDATING_SHEET	= 'FINISH_UPDATING_SHEET';
export const UNAUTHORIZED_SHEET 	= 'UNAUTHORIZED_SHEET';
export const CLEAR_SHEET 	        = 'CLEAR_SHEET';